# Generated by Django 5.2.7 on 2026-08-29 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('trade_industry', models.CharField(db_index=True, help_text='e.g. Industrial Precision Manufacturing, Solar Energy Solutions', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gst_or_cin_number', models.CharField(blank=True, db_index=True, help_text='GSTIN or Corporate ID', max_length=50, null=True)),
                ('location', models.CharField(default='Autonagar Industrial Area, Vijayawada, AP', max_length=255)),
                ('city', models.CharField(db_index=True, default='Vijayawada', max_length=100)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=True)),
                ('verification_badge', models.CharField(default='Verified Enterprise Employer', max_length=100)),
                ('employee_count', models.CharField(default='500-1000 Employees', max_length=50)),
                ('established_year', models.PositiveIntegerField(default=2008)),
                ('contact_person', models.CharField(default='K. Satyanarayana (General Manager - Operations)', max_length=200)),
                ('contact_email', models.EmailField(default='careers@abcindustries.in', max_length=254)),
                ('contact_phone', models.CharField(default='+91 866 2489000', max_length=50)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('bookmarked_worker_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_name', 'city'], name='employers_e_company_26358f_idx'), models.Index(fields=['trade_industry', 'is_verified'], name='employers_e_trade_i_66666b_idx')],
            },
        ),
    ]
