# Generated by Django 5.2.7 on 2026-08-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0001_initial"),
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_candidates",
                        to="employers.employerprofile",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_employers",
                        to="workers.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employer", "worker"),
                        name="unique_employer_saved_worker",
                    )
                ],
            },
        ),
    ]
