export type LanguageCode = 'en' | 'te' | 'hi';

export interface Translations {
  appName: string;
  tagline: string;
  nav: { findWork: string; hireTalent: string; trustScore: string; howItWorks: string; login: string; register: string; dashboard: string; jobs: string; candidates: string; pipeline: string; applications: string; profile: string; analytics: string; verification: string; admin: string; logout: string; voiceSearch: string; switchRole: string; };
  hero: { badge: string; headline: string; headlineHighlight: string; subheadline: string; findWorkBtn: string; hireTalentBtn: string; tryDemoBtn: string; trustedByWorkers: string; activeOpenings: string; verifiedCompanies: string; trustVerifiedBadge: string; };
  problem: { tag: string; title: string; desc: string; traditionalTitle: string; traditionalDesc: string; kaushalTitle: string; kaushalDesc: string; fromLabel: string; toLabel: string; };
  trustSignals: { title: string; subtitle: string; identity: string; skills: string; certifications: string; experience: string; proofOfWork: string; scoreExplanation: string; };
  workerDashboard: { greeting: string; profileStrength: string; trustScore: string; recommendedJobs: string; careerInsights: string; unlockJobs: string; quickApply: string; verified: string; applyNow: string; viewDetails: string; applied: string; shortlisted: string; interview: string; hired: string; };
  employerDashboard: { overview: string; activeJobs: string; applications: string; shortlisted: string; interviews: string; hired: string; postNewJob: string; aiTopCandidates: string; viewPipeline: string; matchScore: string; };
  voiceModal: { title: string; listening: string; clickToSpeak: string; samplePrompt: string; orTry: string; searchResultBtn: string; analyzingVoice: string; };
}

export const translations: Record<LanguageCode, Translations> = {
  en: {
    appName: 'BlueForce',
    tagline: 'Skills that get seen. Work that gets trusted.',
    nav: { findWork: 'Find work', hireTalent: 'Hire talent', trustScore: 'Trust score', howItWorks: 'How it works', login: 'Sign in', register: 'Get started', dashboard: 'Dashboard', jobs: 'Jobs', candidates: 'Candidates', pipeline: 'Pipeline', applications: 'My applications', profile: 'My profile', analytics: 'Analytics', verification: 'Verification centre', admin: 'Admin', logout: 'Log out', voiceSearch: 'Voice search', switchRole: 'Switch view' },
    hero: { badge: 'India\'s verified skills and proof-of-work platform', headline: 'Turn your skills into', headlineHighlight: 'trusted opportunities.', subheadline: 'Build a professional identity, find better industrial work, and be recognised for the work you can prove.', findWorkBtn: 'Find work', hireTalentBtn: 'Hire talent', tryDemoBtn: 'Explore the demo', trustedByWorkers: '12,400+ verified technicians', activeOpenings: '1,850+ active openings', verifiedCompanies: '420+ verified companies', trustVerifiedBadge: 'Identity and skills verified' },
    problem: { tag: 'A better way forward', title: 'Move beyond referrals and middlemen', desc: 'BlueForce makes trusted proof of skills and experience easier to discover.', traditionalTitle: 'The old way', traditionalDesc: 'Unclear information, delayed pay and hiring through referrals.', kaushalTitle: 'The BlueForce way', kaushalDesc: 'Verified credentials, work proof and direct opportunities.', fromLabel: 'From', toLabel: 'To' },
    trustSignals: { title: 'Proof → Trust → Better work → Growth', subtitle: 'A verified professional identity built around what a worker can actually do.', identity: 'Government identity verification', skills: 'Trade skill assessments', certifications: 'NSDC & ITI certifications', experience: 'Employer-verified experience', proofOfWork: 'Photo and video work proof', scoreExplanation: 'A transparent 100-point Trust Score' },
    workerDashboard: { greeting: 'Good morning', profileStrength: 'Profile strength', trustScore: 'Trust score', recommendedJobs: 'Recommended jobs', careerInsights: 'Career insights', unlockJobs: 'Add one more skill to unlock more suitable jobs.', quickApply: 'Quick apply', verified: 'Verified', applyNow: 'Apply now', viewDetails: 'View details', applied: 'Applied', shortlisted: 'Shortlisted', interview: 'Interview', hired: 'Hired' },
    employerDashboard: { overview: 'Recruitment overview', activeJobs: 'Active jobs', applications: 'Applications', shortlisted: 'Shortlisted', interviews: 'Interviews', hired: 'Hired', postNewJob: 'Post a job', aiTopCandidates: 'Top matching candidates', viewPipeline: 'View pipeline', matchScore: 'Match score' },
    voiceModal: { title: 'Voice job search', listening: 'Listening… speak in English, Telugu or Hindi', clickToSpeak: 'Tap the microphone to speak', samplePrompt: 'For example: “Electrician work near Vijayawada above 25 thousand.”', orTry: 'Or choose a sample:', searchResultBtn: 'Find jobs', analyzingVoice: 'Processing voice input…' },
  },
  te: {
    appName: 'బ్లూఫోర్స్',
    tagline: 'గుర్తింపు పొందే నైపుణ్యాలు. నమ్మకమైన పని.',
    nav: { findWork: 'పని కనుగొనండి', hireTalent: 'నైపుణ్యం గల వారిని నియమించండి', trustScore: 'ట్రస్ట్ స్కోర్', howItWorks: 'ఇది ఎలా పనిచేస్తుంది', login: 'సైన్ ఇన్', register: 'ప్రారంభించండి', dashboard: 'డాష్‌బోర్డ్', jobs: 'ఉద్యోగాలు', candidates: 'అభ్యర్థులు', pipeline: 'పైప్‌లైన్', applications: 'నా దరఖాస్తులు', profile: 'నా ప్రొఫైల్', analytics: 'విశ్లేషణలు', verification: 'ధృవీకరణ కేంద్రం', admin: 'అడ్మిన్', logout: 'లాగ్ అవుట్', voiceSearch: 'వాయిస్ సెర్చ్', switchRole: 'వీక్షణ మార్చండి' },
    hero: { badge: 'భారతదేశ ధృవీకరించిన నైపుణ్యాలు మరియు పని రుజువు వేదిక', headline: 'మీ నైపుణ్యాలను మార్చుకోండి', headlineHighlight: 'నమ్మకమైన అవకాశాలుగా.', subheadline: 'వృత్తిపరమైన గుర్తింపును నిర్మించుకోండి, మెరుగైన పారిశ్రామిక ఉద్యోగాలు కనుగొనండి మరియు మీ పని ద్వారా గుర్తింపు పొందండి.', findWorkBtn: 'పని కనుగొనండి', hireTalentBtn: 'నైపుణ్యం గల వారిని నియమించండి', tryDemoBtn: 'డెమో చూడండి', trustedByWorkers: '12,400+ ధృవీకరించిన టెక్నీషియన్లు', activeOpenings: '1,850+ క్రియాశీల ఉద్యోగాలు', verifiedCompanies: '420+ ధృవీకరించిన కంపెనీలు', trustVerifiedBadge: 'గుర్తింపు మరియు నైపుణ్యాలు ధృవీకరించబడ్డాయి' },
    problem: { tag: 'ముందుకు మంచి మార్గం', title: 'పరిచయాలు మరియు మధ్యవర్తులను దాటి ముందుకు వెళ్లండి', desc: 'బ్లూఫోర్స్ నైపుణ్యాలు మరియు అనుభవానికి నమ్మకమైన రుజువును సులభంగా గుర్తించగలిగేలా చేస్తుంది.', traditionalTitle: 'పాత పద్ధతి', traditionalDesc: 'అస్పష్ట సమాచారం, ఆలస్యమైన వేతనాలు మరియు పరిచయాల ద్వారా నియామకం.', kaushalTitle: 'బ్లూఫోర్స్ పద్ధతి', kaushalDesc: 'ధృవీకరించిన పత్రాలు, పని రుజువు మరియు నేరుగా అవకాశాలు.', fromLabel: 'నుండి', toLabel: 'వరకు' },
    trustSignals: { title: 'రుజువు → నమ్మకం → మంచి పని → ఎదుగుదల', subtitle: 'కార్మికుడు నిజంగా చేయగల పనిపై ఆధారపడిన ధృవీకరించిన వృత్తిపరమైన గుర్తింపు.', identity: 'ప్రభుత్వ గుర్తింపు ధృవీకరణ', skills: 'వృత్తి నైపుణ్య పరీక్షలు', certifications: 'NSDC & ITI సర్టిఫికెట్లు', experience: 'యజమాని ధృవీకరించిన అనుభవం', proofOfWork: 'ఫోటో మరియు వీడియో పని రుజువు', scoreExplanation: 'పారదర్శకమైన 100-పాయింట్ల ట్రస్ట్ స్కోర్' },
    workerDashboard: { greeting: 'శుభోదయం', profileStrength: 'ప్రొఫైల్ పూర్తి స్థాయి', trustScore: 'ట్రస్ట్ స్కోర్', recommendedJobs: 'మీకు సిఫార్సు చేసిన ఉద్యోగాలు', careerInsights: 'కెరీర్ సూచనలు', unlockJobs: 'మరిన్ని సరైన ఉద్యోగాలకు ఒక నైపుణ్యాన్ని జోడించండి.', quickApply: 'త్వరిత దరఖాస్తు', verified: 'ధృవీకరించబడింది', applyNow: 'ఇప్పుడే దరఖాస్తు చేయండి', viewDetails: 'వివరాలు చూడండి', applied: 'దరఖాస్తు చేశారు', shortlisted: 'ఎంపిక జాబితా', interview: 'ఇంటర్వ్యూ', hired: 'నియమించారు' },
    employerDashboard: { overview: 'నియామక సారాంశం', activeJobs: 'క్రియాశీల ఉద్యోగాలు', applications: 'దరఖాస్తులు', shortlisted: 'ఎంపిక జాబితా', interviews: 'ఇంటర్వ్యూలు', hired: 'నియమించారు', postNewJob: 'ఉద్యోగాన్ని పోస్ట్ చేయండి', aiTopCandidates: 'ఉత్తమంగా సరిపోలిన అభ్యర్థులు', viewPipeline: 'పైప్‌లైన్ చూడండి', matchScore: 'మ్యాచ్ స్కోర్' },
    voiceModal: { title: 'వాయిస్ జాబ్ సెర్చ్', listening: 'వింటున్నాము… తెలుగు, హిందీ లేదా ఇంగ్లీషులో మాట్లాడండి', clickToSpeak: 'మాట్లాడటానికి మైక్రోఫోన్‌ను నొక్కండి', samplePrompt: 'ఉదాహరణ: “విజయవాడ దగ్గర 25 వేలకు పైగా ఎలక్ట్రీషియన్ పని కావాలి.”', orTry: 'లేదా నమూనాను ఎంచుకోండి:', searchResultBtn: 'ఉద్యోగాలు కనుగొనండి', analyzingVoice: 'వాయిస్ ఇన్‌పుట్‌ను ప్రాసెస్ చేస్తున్నాము…' },
  },
  hi: {
    appName: 'ब्लूफॉर्स',
    tagline: 'हुनर जिसे पहचान मिले। काम जिस पर भरोसा हो।',
    nav: { findWork: 'काम खोजें', hireTalent: 'कुशल कर्मचारी रखें', trustScore: 'ट्रस्ट स्कोर', howItWorks: 'यह कैसे काम करता है', login: 'साइन इन', register: 'शुरू करें', dashboard: 'डैशबोर्ड', jobs: 'नौकरियाँ', candidates: 'उम्मीदवार', pipeline: 'पाइपलाइन', applications: 'मेरे आवेदन', profile: 'मेरी प्रोफ़ाइल', analytics: 'एनालिटिक्स', verification: 'सत्यापन केंद्र', admin: 'एडमिन', logout: 'लॉग आउट', voiceSearch: 'वॉइस सर्च', switchRole: 'व्यू बदलें' },
    hero: { badge: 'भारत का सत्यापित कौशल और काम के प्रमाण का मंच', headline: 'अपने हुनर को बदलें', headlineHighlight: 'भरोसेमंद अवसरों में।', subheadline: 'अपनी पेशेवर पहचान बनाएँ, बेहतर औद्योगिक काम खोजें और अपने प्रमाणित काम की पहचान पाएँ।', findWorkBtn: 'काम खोजें', hireTalentBtn: 'कुशल कर्मचारी रखें', tryDemoBtn: 'डेमो देखें', trustedByWorkers: '12,400+ सत्यापित तकनीशियन', activeOpenings: '1,850+ सक्रिय अवसर', verifiedCompanies: '420+ सत्यापित कंपनियाँ', trustVerifiedBadge: 'पहचान और कौशल सत्यापित' },
    problem: { tag: 'आगे बढ़ने का बेहतर रास्ता', title: 'सिफ़ारिशों और बिचौलियों से आगे बढ़ें', desc: 'ब्लूफॉर्स कौशल और अनुभव के भरोसेमंद प्रमाण को आसानी से खोजने योग्य बनाता है।', traditionalTitle: 'पुराना तरीका', traditionalDesc: 'अस्पष्ट जानकारी, देर से भुगतान और सिफ़ारिशों से भर्ती।', kaushalTitle: 'ब्लूफॉर्स तरीका', kaushalDesc: 'सत्यापित प्रमाण-पत्र, काम का प्रमाण और सीधे अवसर।', fromLabel: 'से', toLabel: 'तक' },
    trustSignals: { title: 'प्रमाण → भरोसा → बेहतर काम → प्रगति', subtitle: 'एक सत्यापित पेशेवर पहचान जो कर्मचारी के वास्तविक कौशल पर आधारित है।', identity: 'सरकारी पहचान सत्यापन', skills: 'ट्रेड कौशल परीक्षण', certifications: 'NSDC और ITI प्रमाण-पत्र', experience: 'नियोक्ता-सत्यापित अनुभव', proofOfWork: 'फोटो और वीडियो काम का प्रमाण', scoreExplanation: 'पारदर्शी 100-पॉइंट ट्रस्ट स्कोर' },
    workerDashboard: { greeting: 'सुप्रभात', profileStrength: 'प्रोफ़ाइल की पूर्णता', trustScore: 'ट्रस्ट स्कोर', recommendedJobs: 'आपके लिए सुझाई गई नौकरियाँ', careerInsights: 'करियर सुझाव', unlockJobs: 'और उपयुक्त नौकरियाँ पाने के लिए एक और कौशल जोड़ें।', quickApply: 'त्वरित आवेदन', verified: 'सत्यापित', applyNow: 'अभी आवेदन करें', viewDetails: 'विवरण देखें', applied: 'आवेदन किया', shortlisted: 'शॉर्टलिस्ट', interview: 'साक्षात्कार', hired: 'नियुक्त' },
    employerDashboard: { overview: 'भर्ती सारांश', activeJobs: 'सक्रिय नौकरियाँ', applications: 'आवेदन', shortlisted: 'शॉर्टलिस्ट', interviews: 'साक्षात्कार', hired: 'नियुक्त', postNewJob: 'नौकरी पोस्ट करें', aiTopCandidates: 'सर्वश्रेष्ठ मिलान वाले उम्मीदवार', viewPipeline: 'पाइपलाइन देखें', matchScore: 'मिलान स्कोर' },
    voiceModal: { title: 'वॉइस जॉब सर्च', listening: 'सुन रहे हैं… हिंदी, तेलुगु या अंग्रेज़ी में बोलें', clickToSpeak: 'बोलने के लिए माइक्रोफ़ोन दबाएँ', samplePrompt: 'उदाहरण: “विजयवाड़ा के पास 25 हज़ार से ऊपर इलेक्ट्रीशियन का काम चाहिए।”', orTry: 'या नमूना चुनें:', searchResultBtn: 'नौकरियाँ खोजें', analyzingVoice: 'वॉइस इनपुट को प्रोसेस किया जा रहा है…' },
  },
};
