# Generated by Django 5.2.7 on 2026-08-29 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_object_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("APPLICATION_RECEIVED", "Application Received"),
                    ("APPLICATION_STATUS_CHANGED", "Application Status Changed"),
                    ("SHORTLISTED", "Candidate Shortlisted"),
                    ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                    ("INTERVIEW_CANCELLED", "Interview Cancelled"),
                    ("VERIFICATION_APPROVED", "Verification Approved"),
                    ("VERIFICATION_REJECTED", "Verification Rejected"),
                    ("JOB_RECOMMENDATION", "Job Recommendation"),
                    ("GENERAL", "General Notice"),
                    ("job_match", "High Match Job Alert"),
                    ("application_update", "Application Status Update"),
                    ("interview", "Interview Scheduled"),
                    ("verification", "Trust Score / Document Update"),
                    ("system", "System Notice"),
                ],
                db_index=True,
                default="GENERAL",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "created_at"],
                name="notificatio_notific_f2e0f7_idx",
            ),
        ),
    ]
