import {
  WorkerProfile,
  EmployerProfile,
  Job,
  Application,
  VerificationDocument,
  PlatformReport,
  NotificationItem,
  User,
} from '../types';

export const mockUsers: User[] = [
  {
    id: 'user_worker_1',
    name: 'Ramesh Kumar',
    email: 'worker@demo.com',
    phone: '+91 98480 12345',
    role: 'worker',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    location: 'Vijayawada, Andhra Pradesh',
    language: 'en',
    isVerified: true,
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'user_employer_1',
    name: 'ABC Industries Recruiter',
    email: 'employer@demo.com',
    phone: '+91 98490 54321',
    role: 'employer',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    location: 'Vijayawada, Andhra Pradesh',
    language: 'en',
    isVerified: true,
    createdAt: '2024-11-15T09:00:00Z',
  },
  {
    id: 'user_admin_1',
    name: 'Platform Moderator',
    email: 'admin@demo.com',
    phone: '+91 99000 11223',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    location: 'Hyderabad, Telangana',
    language: 'en',
    isVerified: true,
    createdAt: '2024-01-01T08:00:00Z',
  },
];

export const defaultWorkerProfile: WorkerProfile = {
  id: 'worker_ramesh_1',
  userId: 'user_worker_1',
  fullName: 'Ramesh Kumar',
  primaryTrade: 'Industrial Electrician & Motor Specialist',
  tagline: 'Certified Industrial Wireman with 5+ years plant & substation commissioning experience',
  bio: 'ITI-certified electrician specializing in high-voltage three-phase motor wiring, switchgear installation, LT/HT panel troubleshooting, and plant power safety audits. Holds valid National Trade Certificate (NTC) and A-grade electrical wireman license.',
  location: 'Vijayawada, Andhra Pradesh',
  city: 'Vijayawada',
  state: 'Andhra Pradesh',
  pinCode: '520001',
  preferredRadiusKm: 25,
  phone: '+91 98480 12345',
  email: 'worker@demo.com',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
  availability: 'available_now',
  expectedSalaryMonthly: { min: 25000, max: 32000 },
  yearsOfExperience: 5,
  education: 'ITI Electrical Diploma (Government ITI Vijayawada)',
  languages: ['Telugu (Fluent)', 'Hindi (Conversational)', 'English (Working)'],
  trustScore: {
    total: 91,
    identity: { score: 20, max: 20, verified: true, label: 'Aadhaar Biometric & Gov ID Verified' },
    certifications: { score: 18, max: 20, verifiedCount: 3, label: 'NSDC & State ITI License Verified' },
    skills: { score: 19, max: 20, testedCount: 4, label: 'Standardized Trade Skill Tests Passed' },
    experience: { score: 15, max: 15, verifiedYears: 5, label: 'Plant Employer Tenures Confirmed' },
    employerReviews: { score: 10, max: 15, avgRating: 4.8, reviewCount: 6, label: 'Direct Supervisor Ratings' },
    completedJobs: { score: 9, max: 10, completedCount: 14, label: 'Verified Commercial Works Completed' },
  },
  profileStrengthPercent: 88,
  skills: [
    {
      id: 'sk_1',
      name: 'Industrial Three-Phase Wiring',
      category: 'Electrical',
      level: 5,
      yearsExperience: 5,
      isVerified: true,
      verificationSource: 'AP State Skill Development Council Test',
      badgeIcon: 'Zap',
    },
    {
      id: 'sk_2',
      name: 'LT/HT Switchgear & Control Panels',
      category: 'Electrical',
      level: 4,
      yearsExperience: 4,
      isVerified: true,
      verificationSource: 'ABC Industries Field Assessment',
      badgeIcon: 'Cpu',
    },
    {
      id: 'sk_3',
      name: 'AC/DC Motor Maintenance & Rewinding',
      category: 'Machinery',
      level: 5,
      yearsExperience: 5,
      isVerified: true,
      verificationSource: 'NSDC Trade Certification',
      badgeIcon: 'RotateCw',
    },
    {
      id: 'sk_4',
      name: 'Industrial Safety & Earthing Protocols',
      category: 'Safety',
      level: 4,
      yearsExperience: 4,
      isVerified: true,
      verificationSource: 'OSHA / Plant Safety Audit',
      badgeIcon: 'ShieldCheck',
    },
    {
      id: 'sk_5',
      name: 'Basic PLC Troubleshooting',
      category: 'Automation',
      level: 2,
      yearsExperience: 1,
      isVerified: false,
      badgeIcon: 'Sliders',
    },
  ],
  certifications: [
    {
      id: 'cert_1',
      title: 'National Trade Certificate (NTC) — Electrician Trade',
      issuingBody: 'National Council for Vocational Training (NCVT / DGT)',
      issueDate: '2020-07-15',
      credentialId: 'NCVT-EL-2020-8849',
      documentUrl: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=600&auto=format&fit=crop&q=80',
      verificationStatus: 'verified',
      verifiedAt: '2025-01-12T11:00:00Z',
    },
    {
      id: 'cert_2',
      title: 'Government Wireman Competency Certificate (A-Grade)',
      issuingBody: 'Chief Electrical Inspectorate to Government (CEIG), AP',
      issueDate: '2021-03-20',
      credentialId: 'CEIG-AP-LIC-44912',
      documentUrl: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
      verificationStatus: 'verified',
      verifiedAt: '2025-01-14T14:30:00Z',
    },
    {
      id: 'cert_3',
      title: 'Solar Photovoltaic System Installer Certification',
      issuingBody: 'Skill Council for Green Jobs (SCGJ / NSDC)',
      issueDate: '2023-09-10',
      credentialId: 'SCGJ-PV-2023-1092',
      documentUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
      verificationStatus: 'verified',
      verifiedAt: '2025-01-15T09:15:00Z',
    },
  ],
  experience: [
    {
      id: 'exp_1',
      jobTitle: 'Senior Plant Electrician',
      companyName: 'ABC Industries Ltd.',
      location: 'Autonagar Industrial Area, Vijayawada',
      startDate: '2022-04-01',
      isCurrent: true,
      description: 'Managed round-the-clock maintenance of 440V distribution panels, motor control centers (MCC), and 500kVA backup diesel generator synchronizers. Reduced plant downtime by 35%.',
      skillsUsed: ['LT Panels', 'Motor Rewinding', 'Capacitor Banks', 'Safety Audits'],
      isEmployerVerified: true,
      verifierContact: 'hr@abcindustries.in',
    },
    {
      id: 'exp_2',
      jobTitle: 'Substation Technician',
      companyName: 'Sri Balaji Electrical Contractors',
      location: 'Guntur, Andhra Pradesh',
      startDate: '2020-08-01',
      endDate: '2022-03-31',
      isCurrent: false,
      description: 'Handled erection, testing, and commissioning of 33/11kV power transformers and circuit breakers for commercial industrial parks.',
      skillsUsed: ['Transformer Maintenance', 'Cable Splicing', 'Earthing Grid Setup'],
      isEmployerVerified: true,
      verifierContact: 'contact@balajielectricals.com',
    },
  ],
  proofOfWork: [
    {
      id: 'pow_1',
      title: '250 kVA Industrial Motor Control Center Installation',
      description: 'Fabricated and wired full starter panels with star-delta contactors, thermal overload relays, and digital energy meters for a manufacturing plant.',
      category: 'Industrial Electrical',
      images: [
        'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
      ],
      skillsDemonstrated: ['MCC Panel Wiring', 'Cable Routing', 'Protection Relays'],
      clientOrEmployer: 'ABC Industries Ltd.',
      location: 'Vijayawada',
      completionDate: '2024-11-15',
      isVerified: true,
      verifiedBy: 'Senior Electrical Engineer, ABC Industries',
      rating: 5,
    },
    {
      id: 'pow_2',
      title: '100 kW Commercial Rooftop Solar Inverter Sync',
      description: 'Completed DC string cabling, solar array junction box termination, and grid-tied inverter synchronization with anti-islanding safety tests.',
      category: 'Renewable Power',
      images: [
        'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80',
      ],
      skillsDemonstrated: ['Solar DC Cabling', 'Inverter Sync', 'Surge Protection'],
      clientOrEmployer: 'GreenEra Commercial Solutions',
      location: 'Gannavaram',
      completionDate: '2024-07-20',
      isVerified: true,
      verifiedBy: 'Site In-Charge, GreenEra',
      rating: 5,
    },
  ],
  reviews: [
    {
      id: 'rev_1',
      reviewerName: 'K. Satyanarayana',
      reviewerCompany: 'Plant Manager, ABC Industries',
      rating: 5,
      comment: 'Ramesh is an exceptional technician. His understanding of high-voltage motor schematics and adherence to safety protocols is top notch. Always reliable.',
      date: '2024-12-05',
      verifiedHire: true,
    },
    {
      id: 'rev_2',
      reviewerName: 'R. Venkat',
      reviewerCompany: 'Project Lead, GreenEra Solar',
      rating: 4.8,
      comment: 'Clean wiring, timely execution, and passed inspection without single discrepancy. Highly recommended for heavy commercial installations.',
      date: '2024-08-10',
      verifiedHire: true,
    },
  ],
  recommendedSkills: [
    {
      skill: 'PLC Troubleshooting & Ladder Logic',
      unlocksJobsCount: 18,
      avgSalaryBoost: '+₹8,000 / month',
    },
    {
      skill: 'SCADA System Monitoring',
      unlocksJobsCount: 12,
      avgSalaryBoost: '+₹6,500 / month',
    },
    {
      skill: 'Variable Frequency Drives (VFD) Calibration',
      unlocksJobsCount: 9,
      avgSalaryBoost: '+₹4,500 / month',
    },
  ],
  bookmarkedJobIds: ['job_1', 'job_3'],
};

export const mockCandidates: WorkerProfile[] = [
  defaultWorkerProfile,
  {
    id: 'worker_suresh_2',
    userId: 'user_worker_2',
    fullName: 'Suresh Reddy',
    primaryTrade: 'CNC Machinist & Lathe Operator',
    tagline: 'Expert in CNC Milling, Fanuc Controls & 5-Axis Precision Turning',
    bio: '6 years of experience operating DMG Mori and Haas CNC milling and lathe machines in aerospace and automotive vendor plants. Skilled in reading technical engineering drawings and precision G-code editing.',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    pinCode: '500037',
    preferredRadiusKm: 30,
    phone: '+91 98490 22334',
    email: 'suresh.reddy@worker.in',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    availability: 'available_now',
    expectedSalaryMonthly: { min: 28000, max: 35000 },
    yearsOfExperience: 6,
    education: 'Diploma in Mechanical Engineering (Polytechnic)',
    languages: ['Telugu', 'Hindi', 'English'],
    trustScore: {
      total: 88,
      identity: { score: 20, max: 20, verified: true, label: 'Gov ID Verified' },
      certifications: { score: 17, max: 20, verifiedCount: 2, label: 'Mechanical Trade Diploma' },
      skills: { score: 18, max: 20, testedCount: 3, label: 'Precision CNC Skill Assessment' },
      experience: { score: 14, max: 15, verifiedYears: 6, label: 'Machining Plant History' },
      employerReviews: { score: 11, max: 15, avgRating: 4.7, reviewCount: 4, label: 'Foreman Ratings' },
      completedJobs: { score: 8, max: 10, completedCount: 11, label: 'Production Runs Completed' },
    },
    profileStrengthPercent: 85,
    skills: [
      { id: 'sk_cnc1', name: 'CNC Lathe & Turning', category: 'Machining', level: 5, yearsExperience: 6, isVerified: true, badgeIcon: 'Tool' },
      { id: 'sk_cnc2', name: 'Fanuc & Siemens Controls', category: 'Controls', level: 4, yearsExperience: 5, isVerified: true, badgeIcon: 'Cpu' },
      { id: 'sk_cnc3', name: 'GD&T Blueprint Reading', category: 'Engineering', level: 5, yearsExperience: 6, isVerified: true, badgeIcon: 'FileText' },
    ],
    certifications: [
      { id: 'cert_cnc1', title: 'CNC Machine Programming & Operation', issuingBody: 'Advanced Training Institute (ATI Hyderabad)', issueDate: '2019-06-10', credentialId: 'ATI-HYD-CNC-993', verificationStatus: 'verified' },
    ],
    experience: [
      { id: 'exp_cnc1', jobTitle: 'Senior CNC Operator', companyName: 'Deccan Precision Tech', location: 'Sanath Nagar, Hyderabad', startDate: '2021-01-10', isCurrent: true, description: 'Produced high-precision hydraulic valve housings with 10-micron tolerances.', skillsUsed: ['Fanuc CNC', 'Micrometers', 'G-Code'], isEmployerVerified: true },
    ],
    proofOfWork: [
      { id: 'pow_cnc1', title: 'Turbine Impeller Precision Turning', description: 'Programmed 4-axis lathe for stainless steel impeller fabrication with zero defect tolerance.', category: 'Precision Turning', images: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80'], skillsDemonstrated: ['4-Axis Machining', 'Titanium Milling'], clientOrEmployer: 'Deccan Precision Tech', location: 'Hyderabad', completionDate: '2024-10-02', isVerified: true },
    ],
    reviews: [
      { id: 'rev_cnc1', reviewerName: 'M. Srinivas', reviewerCompany: 'Production Head, Deccan Precision', rating: 4.8, comment: 'High precision and zero scrap rate. Extremely disciplined operator.', date: '2024-11-20', verifiedHire: true },
    ],
    recommendedSkills: [
      { skill: '5-Axis Mastercam Simulation', unlocksJobsCount: 14, avgSalaryBoost: '+₹7,000 / month' },
    ],
    bookmarkedJobIds: [],
  },
  {
    id: 'worker_priya_3',
    userId: 'user_worker_3',
    fullName: 'Priya Devi',
    primaryTrade: 'Solar PV Systems & Renewable Tech',
    tagline: 'SCGJ Certified Solar Technician with 4+ years in Megawatt Solar Farms',
    bio: 'Specialized in utility-scale ground mount and industrial rooftop solar installation, DC string testing, string combiner boxes, and inverter commissioning.',
    location: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    pinCode: '560058',
    preferredRadiusKm: 35,
    phone: '+91 97410 88776',
    email: 'priya.devi@worker.in',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    availability: 'available_now',
    expectedSalaryMonthly: { min: 26000, max: 34000 },
    yearsOfExperience: 4,
    education: 'ITI Electrician & Diploma in Green Energy',
    languages: ['Kannada', 'Telugu', 'Hindi', 'English'],
    trustScore: {
      total: 94,
      identity: { score: 20, max: 20, verified: true, label: 'Identity Verified' },
      certifications: { score: 20, max: 20, verifiedCount: 3, label: 'SCGJ & Suryamitra Verified' },
      skills: { score: 19, max: 20, testedCount: 4, label: 'Solar Electrical Verified' },
      experience: { score: 15, max: 15, verifiedYears: 4, label: 'Solar Farm Experience' },
      employerReviews: { score: 11, max: 15, avgRating: 4.9, reviewCount: 5, label: 'EPC Ratings' },
      completedJobs: { score: 9, max: 10, completedCount: 16, label: 'MW Installations' },
    },
    profileStrengthPercent: 92,
    skills: [
      { id: 'sk_sol1', name: 'Solar PV String Inverter Setup', category: 'Solar', level: 5, yearsExperience: 4, isVerified: true, badgeIcon: 'Sun' },
      { id: 'sk_sol2', name: 'Megger & DC Insulation Testing', category: 'Testing', level: 5, yearsExperience: 4, isVerified: true, badgeIcon: 'Activity' },
      { id: 'sk_sol3', name: 'HT Grid Synchronizer', category: 'Grid', level: 4, yearsExperience: 3, isVerified: true, badgeIcon: 'Zap' },
    ],
    certifications: [
      { id: 'cert_sol1', title: 'Suryamitra Skill Development Program Certified', issuingBody: 'National Institute of Solar Energy (NISE)', issueDate: '2021-02-15', credentialId: 'NISE-SM-2021-440', verificationStatus: 'verified' },
    ],
    experience: [
      { id: 'exp_sol1', jobTitle: 'Lead Solar Technician', companyName: 'Deccan Solar Technologies', location: 'Peenya, Bengaluru', startDate: '2021-05-01', isCurrent: true, description: 'Supervised 2.5MW commercial rooftop PV installation and SCADA telemetry setup.', skillsUsed: ['DC Combiner', 'Grid Sync', 'MC4 Crimping'], isEmployerVerified: true },
    ],
    proofOfWork: [
      { id: 'pow_sol1', title: '2 MW Industrial Rooftop Solar Array', description: 'Commissioned 4,200 monocrystalline panels with zero ground faults.', category: 'Solar Installation', images: ['https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80'], skillsDemonstrated: ['Solar Array', 'Combiner Box'], clientOrEmployer: 'Deccan Solar Technologies', location: 'Bengaluru', completionDate: '2024-09-15', isVerified: true },
    ],
    reviews: [
      { id: 'rev_sol1', reviewerName: 'Arun Varma', reviewerCompany: 'Director, Deccan Solar', rating: 5, comment: 'Exceptional safety discipline and speed of commissioning. A role model technician.', date: '2024-10-18', verifiedHire: true },
    ],
    recommendedSkills: [
      { skill: 'Battery Energy Storage Systems (BESS)', unlocksJobsCount: 15, avgSalaryBoost: '+₹9,000 / month' },
    ],
    bookmarkedJobIds: [],
  },
  {
    id: 'worker_manjunath_4',
    userId: 'user_worker_4',
    fullName: 'Manjunath Patil',
    primaryTrade: 'TIG/MIG Pipe Welder & Structural Fabricator',
    tagline: 'ASME 6G Certified Welder with 7+ years in Pressure Vessel & Piping',
    bio: 'Specialist in stainless steel and carbon steel TIG (GTAW) and MIG (GMAW) welding for chemical plants, boilers, and heavy structural frameworks.',
    location: 'Pune, Maharashtra',
    city: 'Pune',
    state: 'Maharashtra',
    pinCode: '411018',
    preferredRadiusKm: 30,
    phone: '+91 98230 44556',
    email: 'manju.patil@worker.in',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    availability: 'in_two_weeks',
    expectedSalaryMonthly: { min: 30000, max: 38000 },
    yearsOfExperience: 7,
    education: 'ITI Welder (National Council for Vocational Training)',
    languages: ['Marathi', 'Hindi', 'English'],
    trustScore: {
      total: 89,
      identity: { score: 20, max: 20, verified: true, label: 'Identity Verified' },
      certifications: { score: 18, max: 20, verifiedCount: 2, label: 'ASME 6G Certification' },
      skills: { score: 18, max: 20, testedCount: 3, label: 'X-Ray Quality Welding' },
      experience: { score: 15, max: 15, verifiedYears: 7, label: 'Plant Fabrication Tenures' },
      employerReviews: { score: 10, max: 15, avgRating: 4.7, reviewCount: 5, label: 'QA Inspector Reviews' },
      completedJobs: { score: 8, max: 10, completedCount: 12, label: 'Pipeline Projects' },
    },
    profileStrengthPercent: 86,
    skills: [
      { id: 'sk_wld1', name: '6G Pipe TIG Welding (GTAW)', category: 'Welding', level: 5, yearsExperience: 7, isVerified: true, badgeIcon: 'Flame' },
      { id: 'sk_wld2', name: 'Structural MIG Welding (GMAW)', category: 'Welding', level: 5, yearsExperience: 6, isVerified: true, badgeIcon: 'Flame' },
      { id: 'sk_wld3', name: 'X-Ray & Radiographic Weld Quality', category: 'QA', level: 4, yearsExperience: 5, isVerified: true, badgeIcon: 'Shield' },
    ],
    certifications: [
      { id: 'cert_wld1', title: 'ASME Section IX 6G Pipe Welder Qualification', issuingBody: 'Indian Institute of Welding (IIW)', issueDate: '2020-04-12', credentialId: 'IIW-6G-2020-911', verificationStatus: 'verified' },
    ],
    experience: [
      { id: 'exp_wld1', jobTitle: 'Lead Pressure Welder', companyName: 'Pune Heavy Engineering Works', location: 'Pimpri-Chinchwad, Pune', startDate: '2020-02-01', isCurrent: true, description: 'Handled high pressure steam piping with 99.4% radiographic weld pass rate.', skillsUsed: ['6G TIG', 'Argon Purging', 'Hydro Testing'], isEmployerVerified: true },
    ],
    proofOfWork: [
      { id: 'pow_wld1', title: 'High Pressure Steam Header Line TIG Welds', description: 'Welded 8-inch schedule 80 carbon steel pipe with full penetration root pass.', category: 'Pipe Welding', images: ['https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=800&auto=format&fit=crop&q=80'], skillsDemonstrated: ['Argon Shielding', 'Radiography'], clientOrEmployer: 'Pune Heavy Engineering Works', location: 'Pune', completionDate: '2024-11-01', isVerified: true },
    ],
    reviews: [
      { id: 'rev_wld1', reviewerName: 'D. Gokhale', reviewerCompany: 'Welding QA Lead, Pune Heavy Engg', rating: 4.9, comment: 'Flawless root passes and excellent torch control. Always clear in NDT checks.', date: '2024-12-01', verifiedHire: true },
    ],
    recommendedSkills: [
      { skill: 'Orbital Automated TIG Welding', unlocksJobsCount: 11, avgSalaryBoost: '+₹8,500 / month' },
    ],
    bookmarkedJobIds: [],
  },
];

export const mockEmployerProfile: EmployerProfile = {
  id: 'employer_abc_1',
  userId: 'user_employer_1',
  companyName: 'ABC Industries Ltd.',
  tradeIndustry: 'Industrial Precision Manufacturing & Power Engineering',
  tagline: 'Leading manufacturer of heavy electrical switchgear and automotive components since 2008',
  description: 'ABC Industries operates state-of-the-art manufacturing plants across Andhra Pradesh and Telangana. We employ over 600 skilled technicians, electricians, machinists, and engineers with direct PF/ESI benefits and safe working standards.',
  gstOrCinNumber: 'GSTIN: 37AAACA4918L1Z9',
  location: 'Autonagar Industrial Estate, Vijayawada, AP',
  city: 'Vijayawada',
  state: 'Andhra Pradesh',
  logoUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&auto=format&fit=crop&q=80',
  isVerified: true,
  verificationBadge: 'Verified Enterprise Employer',
  employeeCount: '500-1000 Employees',
  establishedYear: 2008,
  contactPerson: 'K. Satyanarayana (General Manager - Operations)',
  contactEmail: 'careers@abcindustries.in',
  contactPhone: '+91 866 2489000',
  website: 'https://abcindustries-demo.in',
  bookmarkedWorkerIds: ['worker_ramesh_1', 'worker_priya_3'],
};

export const mockJobs: Job[] = [
  {
    id: 'job_1',
    employerId: 'employer_abc_1',
    companyName: 'ABC Industries Ltd.',
    companyLogoUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&auto=format&fit=crop&q=80',
    isCompanyVerified: true,
    title: 'Industrial Electrician & Substation Technician',
    tradeCategory: 'Electrical',
    location: 'Autonagar, Vijayawada',
    city: 'Vijayawada',
    distanceKm: 6,
    salaryMin: 25000,
    salaryMax: 32000,
    salaryPeriod: 'monthly',
    experienceRequiredYears: 4,
    jobType: 'Full-time',
    shift: 'Day Shift',
    openings: 4,
    joiningDate: 'Immediate / Within 15 Days',
    deadlineDate: '2026-03-31',
    postedAt: '2 days ago',
    requiredSkills: ['Industrial Three-Phase Wiring', 'LT/HT Switchgear', 'Motor Maintenance', 'Plant Safety'],
    preferredSkills: ['PLC Troubleshooting', 'Capacitor Bank Calibration'],
    requiredCertifications: ['ITI Electrician Diploma', 'A-Grade Wireman License'],
    description: 'Looking for a certified Industrial Electrician to supervise plant electrical distribution, perform preventative maintenance on 440V motor control centers, and maintain power reliability.',
    benefits: ['PF & ESI Provided', 'Subsidized Canteen', 'Annual Bonus', 'Overtime Allowance (1.5x)', 'Safety Gear Provided'],
    workAddress: 'Plot 42, Phase-2, Autonagar Industrial Area, Vijayawada, AP',
    status: 'active',
    applicationsCount: 24,
    matchData: {
      matchPercentage: 94,
      skillCompatibility: { score: 45, max: 50, details: 'Matches 4 out of 4 core required skills + 1 bonus skill' },
      experienceScore: { score: 20, max: 20, details: '5 years experience (exceeds 4 years requirement)' },
      locationScore: { score: 14, max: 15, details: 'Located 6 km away within preferred 25 km commute radius' },
      certificationScore: { score: 5, max: 5, details: 'ITI Diploma & CEIG Wireman license verified by platform' },
      availabilityScore: { score: 10, max: 10, details: 'Worker marked Available Immediately' },
      reasons: [
        'Verified Industrial Three-Phase Wiring skill (5★ rating)',
        'ITI Electrical Diploma verified via NCVT registry',
        'Directly located in Vijayawada (6 km away)',
        'Strong supervisory reviews from previous plant tenures',
      ],
    },
  },
  {
    id: 'job_2',
    employerId: 'employer_deccan_solar',
    companyName: 'Deccan Solar Technologies',
    companyLogoUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=200&auto=format&fit=crop&q=80',
    isCompanyVerified: true,
    title: 'Commercial Solar PV Rooftop Lead Technician',
    tradeCategory: 'Solar & Renewable Energy',
    location: 'Gannavaram / Vijayawada Airport Corridor',
    city: 'Vijayawada',
    distanceKm: 14,
    salaryMin: 24000,
    salaryMax: 30000,
    salaryPeriod: 'monthly',
    experienceRequiredYears: 3,
    jobType: 'Full-time',
    shift: 'Day Shift',
    openings: 6,
    joiningDate: 'Within 7 Days',
    deadlineDate: '2026-04-15',
    postedAt: '1 day ago',
    requiredSkills: ['Solar PV String Inverter Setup', 'DC Insulation Testing', 'Industrial Safety'],
    requiredCertifications: ['Suryamitra / SCGJ Certification', 'ITI Electrical'],
    description: 'Lead rooftop solar PV installations for commercial cold storage facilities and manufacturing units. Involves structure alignment, DC wiring, inverter commissioning, and grid synchronization.',
    benefits: ['Travel Allowance', 'PF & ESI', 'Accidental Insurance (₹5 Lakh)', 'Performance Incentives'],
    workAddress: 'Tech Park Zone, Gannavaram, Vijayawada',
    status: 'active',
    applicationsCount: 18,
    matchData: {
      matchPercentage: 91,
      skillCompatibility: { score: 43, max: 50, details: 'Matches solar inverter, testing & electrical wiring skills' },
      experienceScore: { score: 20, max: 20, details: '5 years experience (exceeds 3 years requirement)' },
      locationScore: { score: 13, max: 15, details: '14 km commute distance' },
      certificationScore: { score: 5, max: 5, details: 'Skill Council for Green Jobs verified' },
      availabilityScore: { score: 10, max: 10, details: 'Ready for immediate onboarding' },
      reasons: [
        'SCGJ Solar PV Certificate verified on profile',
        'Past verified proof-of-work in 100kW rooftop installation',
        'Immediate joining availability',
      ],
    },
  },
  {
    id: 'job_3',
    employerId: 'employer_southern_fab',
    companyName: 'Southern Precision Fab & Engineering',
    companyLogoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=200&auto=format&fit=crop&q=80',
    isCompanyVerified: true,
    title: 'CNC Lathe & Milling Machine Operator',
    tradeCategory: 'Machining & Tooling',
    location: 'Patancheru Industrial Area, Hyderabad',
    city: 'Hyderabad',
    distanceKm: 270,
    salaryMin: 28000,
    salaryMax: 36000,
    salaryPeriod: 'monthly',
    experienceRequiredYears: 4,
    jobType: 'Full-time',
    shift: 'Rotational',
    openings: 5,
    joiningDate: 'Within 30 Days',
    deadlineDate: '2026-04-10',
    postedAt: '3 days ago',
    requiredSkills: ['CNC Lathe & Turning', 'Fanuc & Siemens Controls', 'GD&T Blueprint Reading'],
    requiredCertifications: ['Diploma Mechanical or ITI Machinist'],
    description: 'Requires experienced CNC turner to produce automotive components. Must possess strong drawing interpretation skills and tool offset adjustment experience.',
    benefits: ['Accommodation Allowance', 'Subsidized Food', 'PF / Gratuity', 'Medical Cover'],
    workAddress: 'Phase 3, Patancheru, Hyderabad',
    status: 'active',
    applicationsCount: 31,
    matchData: {
      matchPercentage: 72,
      skillCompatibility: { score: 32, max: 50, details: 'Trade is Machining (Worker primary trade is Electrical)' },
      experienceScore: { score: 20, max: 20, details: '5 years general plant experience' },
      locationScore: { score: 6, max: 15, details: 'Inter-city relocation required (Vijayawada -> Hyderabad)' },
      certificationScore: { score: 4, max: 5, details: 'Technical ITI background' },
      availabilityScore: { score: 10, max: 10, details: 'Available' },
      reasons: [
        'Requires CNC Turning skills which are secondary for Ramesh',
        'Different city location (relocation required)',
      ],
    },
  },
  {
    id: 'job_4',
    employerId: 'employer_abc_1',
    companyName: 'ABC Industries Ltd.',
    companyLogoUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&auto=format&fit=crop&q=80',
    isCompanyVerified: true,
    title: 'TIG / MIG Pipeline Welder (Pressure Vessels)',
    tradeCategory: 'Welding & Fabrication',
    location: 'Autonagar, Vijayawada',
    city: 'Vijayawada',
    distanceKm: 6,
    salaryMin: 26000,
    salaryMax: 34000,
    salaryPeriod: 'monthly',
    experienceRequiredYears: 4,
    jobType: 'Full-time',
    shift: 'Day Shift',
    openings: 3,
    joiningDate: 'Immediate',
    deadlineDate: '2026-03-25',
    postedAt: '4 days ago',
    requiredSkills: ['6G Pipe TIG Welding', 'Structural MIG Welding', 'Radiographic Quality'],
    requiredCertifications: ['ITI Welder', 'ASME / IIW 6G Certificate'],
    description: 'Perform heavy fabrication and high-pressure steam pipe welding. Welds will undergo radiographic NDT and hydrostatic pressure tests.',
    benefits: ['PF & ESI', 'Welding Milk/Health Allowance', 'Overtime at Double Rate', 'Safety PPE Provided'],
    workAddress: 'Autonagar Heavy Fabrication Yard, Vijayawada',
    status: 'active',
    applicationsCount: 15,
  },
  {
    id: 'job_5',
    employerId: 'employer_apex_logistics',
    companyName: 'Apex Logistics & Cold Storage Infrastructure',
    companyLogoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=200&auto=format&fit=crop&q=80',
    isCompanyVerified: true,
    title: 'Heavy Diesel Fleet Mechanic & Hydraulics Technician',
    tradeCategory: 'Automotive & Heavy Vehicles',
    location: 'Ennore Port Corridor, Chennai',
    city: 'Chennai',
    distanceKm: 420,
    salaryMin: 27000,
    salaryMax: 36000,
    salaryPeriod: 'monthly',
    experienceRequiredYears: 5,
    jobType: 'Full-time',
    shift: 'Rotational',
    openings: 4,
    joiningDate: 'Within 20 Days',
    deadlineDate: '2026-04-20',
    postedAt: '5 days ago',
    requiredSkills: ['Diesel Engine Overhaul', 'Hydraulic Systems Repair', 'Air Brake Troubleshooting'],
    requiredCertifications: ['ITI Mechanic Motor Vehicle (MMV) / Diesel Mechanic'],
    description: 'Diagnose and overhaul multi-axle BharatBenz and Tata heavy commercial prime movers, hydraulic tail lifts, and reefer unit auxiliary engines.',
    benefits: ['PF/ESI', 'Free Quarters Accommodation', 'Annual Retention Bonus', 'Canteen'],
    workAddress: 'Apex Port Logistics Hub, Ennore, Chennai',
    status: 'active',
    applicationsCount: 20,
  },
  {
    id: 'job_6',
    employerId: 'employer_abc_1',
    companyName: 'ABC Industries Ltd.',
    companyLogoUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&auto=format&fit=crop&q=80',
    isCompanyVerified: true,
    title: 'Plant Automation & PLC Maintenance Specialist',
    tradeCategory: 'Automation & Instrumentation',
    location: 'Autonagar, Vijayawada',
    city: 'Vijayawada',
    distanceKm: 6,
    salaryMin: 32000,
    salaryMax: 42000,
    salaryPeriod: 'monthly',
    experienceRequiredYears: 4,
    jobType: 'Full-time',
    shift: 'Day Shift',
    openings: 2,
    joiningDate: 'Within 15 Days',
    deadlineDate: '2026-04-30',
    postedAt: 'Just now',
    requiredSkills: ['PLC Troubleshooting & Ladder Logic', 'SCADA Monitoring', 'Sensor Calibration', 'VFD Drives'],
    requiredCertifications: ['Diploma in Electrical & Electronics / Automation'],
    description: 'Maintain automated conveyor lines, calibrate industrial PID sensors, troubleshoot PLC inputs/outputs, and program variable frequency drives.',
    benefits: ['Higher Pay Scale', 'Tech Certification Support', 'Health Insurance', 'Performance Bonus'],
    workAddress: 'Automation Section, ABC Industries, Vijayawada',
    status: 'active',
    applicationsCount: 9,
    matchData: {
      matchPercentage: 78,
      skillCompatibility: { score: 35, max: 50, details: 'Strong electrical base, but lacks advanced PLC ladder certification' },
      experienceScore: { score: 20, max: 20, details: '5 years plant experience matches perfectly' },
      locationScore: { score: 15, max: 15, details: 'Same industrial area (6 km)' },
      certificationScore: { score: 3, max: 5, details: 'ITI Electrician verified; PLC specialized diploma pending' },
      availabilityScore: { score: 10, max: 10, details: 'Available immediately' },
      reasons: [
        'High location & plant familiarity match',
        'One skill away: Complete PLC Troubleshooting to boost match to 96%',
      ],
    },
  },
];

export const mockApplications: Application[] = [
  {
    id: 'app_1',
    jobId: 'job_1',
    workerId: 'worker_ramesh_1',
    employerId: 'employer_abc_1',
    jobTitle: 'Industrial Electrician & Substation Technician',
    companyName: 'ABC Industries Ltd.',
    workerName: 'Ramesh Kumar',
    workerTrade: 'Industrial Electrician',
    workerAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    workerTrustScore: 91,
    workerExperienceYears: 5,
    workerLocation: 'Vijayawada, AP (6 km)',
    matchScore: 94,
    topSkills: ['Industrial Wiring', 'LT/HT Switchgear', 'Motor Maintenance'],
    appliedDate: '2026-02-25',
    currentStage: 'Interview',
    timeline: [
      { stage: 'Applied', timestamp: '2026-02-25 10:30 AM', note: 'Application submitted with verified Trust Score (91/100)', completed: true },
      { stage: 'Screening', timestamp: '2026-02-26 02:15 PM', note: 'AI Matching scored 94%. ITI certificate verified automatically.', completed: true },
      { stage: 'Shortlisted', timestamp: '2026-02-27 11:00 AM', note: 'Selected for trade test by Plant Manager K. Satyanarayana', completed: true },
      { stage: 'Interview', timestamp: '2026-02-28 09:30 AM', note: 'Practical motor wiring trade test scheduled for Monday 10:00 AM', completed: true },
      { stage: 'Selected', timestamp: '', note: 'Pending final review post-trade test', completed: false },
      { stage: 'Hired', timestamp: '', note: 'Final offer letter & plant joining badge', completed: false },
    ],
    interview: {
      id: 'int_1',
      date: '2026-03-02',
      time: '10:00 AM IST',
      type: 'In-person Trade Test',
      locationOrLink: 'ABC Industries Main Plant, Maintenance Bay 4, Autonagar, Vijayawada',
      instructions: 'Please bring original A-grade wireman license and wear standard safety boots. Tools for star-delta panel wiring will be provided at the workshop.',
      interviewerName: 'K. Satyanarayana (General Manager - Operations)',
      status: 'scheduled',
    },
    employerNotes: 'Excellent proof of work in 250kVA panel installation. Strong candidate for morning shift plant lead.',
    rating: 5,
  },
  {
    id: 'app_2',
    jobId: 'job_2',
    workerId: 'worker_ramesh_1',
    employerId: 'employer_deccan_solar',
    jobTitle: 'Commercial Solar PV Rooftop Lead Technician',
    companyName: 'Deccan Solar Technologies',
    workerName: 'Ramesh Kumar',
    workerTrade: 'Industrial Electrician',
    workerAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    workerTrustScore: 91,
    workerExperienceYears: 5,
    workerLocation: 'Vijayawada, AP (14 km)',
    matchScore: 91,
    topSkills: ['Solar PV Setup', 'DC Cabling', 'Inverter Sync'],
    appliedDate: '2026-02-26',
    currentStage: 'Shortlisted',
    timeline: [
      { stage: 'Applied', timestamp: '2026-02-26 04:00 PM', note: 'Applied via 1-click verified credentials', completed: true },
      { stage: 'Screening', timestamp: '2026-02-27 10:00 AM', note: 'Green Energy SCGJ Certificate verified', completed: true },
      { stage: 'Shortlisted', timestamp: '2026-02-28 01:00 PM', note: 'Shortlisted by HR. Scheduling video call.', completed: true },
      { stage: 'Interview', timestamp: '', note: 'Interview slot to be picked', completed: false },
      { stage: 'Selected', timestamp: '', note: 'Offer negotiation', completed: false },
      { stage: 'Hired', timestamp: '', note: 'Joining process', completed: false },
    ],
  },
  {
    id: 'app_3',
    jobId: 'job_1',
    workerId: 'worker_priya_3',
    employerId: 'employer_abc_1',
    jobTitle: 'Industrial Electrician & Substation Technician',
    companyName: 'ABC Industries Ltd.',
    workerName: 'Priya Devi',
    workerTrade: 'Solar & Electrical Technician',
    workerAvatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    workerTrustScore: 94,
    workerExperienceYears: 4,
    workerLocation: 'Bengaluru (Open to relocation)',
    matchScore: 89,
    topSkills: ['HT Grid Synchronizer', 'Testing', 'Panel Wiring'],
    appliedDate: '2026-02-24',
    currentStage: 'Selected',
    timeline: [
      { stage: 'Applied', timestamp: '2026-02-24 11:00 AM', note: 'Application received', completed: true },
      { stage: 'Screening', timestamp: '2026-02-25 09:00 AM', note: 'Screened with 94 Trust Score', completed: true },
      { stage: 'Shortlisted', timestamp: '2026-02-25 04:00 PM', note: 'Shortlisted for technical round', completed: true },
      { stage: 'Interview', timestamp: '2026-02-27 02:00 PM', note: 'Video technical round completed', completed: true },
      { stage: 'Selected', timestamp: '2026-02-28 03:30 PM', note: 'Selected for Substation Lead position with ₹34,000 package', completed: true },
      { stage: 'Hired', timestamp: '', note: 'Awaiting candidate acceptance', completed: false },
    ],
  },
  {
    id: 'app_4',
    jobId: 'job_1',
    workerId: 'worker_manjunath_4',
    employerId: 'employer_abc_1',
    jobTitle: 'Industrial Electrician & Substation Technician',
    companyName: 'ABC Industries Ltd.',
    workerName: 'Manjunath Patil',
    workerTrade: 'Pipe Welder & Fabricator',
    workerAvatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    workerTrustScore: 89,
    workerExperienceYears: 7,
    workerLocation: 'Pune (Relocating)',
    matchScore: 79,
    topSkills: ['6G TIG Welding', 'Fabrication', 'Safety'],
    appliedDate: '2026-02-26',
    currentStage: 'Screening',
    timeline: [
      { stage: 'Applied', timestamp: '2026-02-26 09:00 AM', note: 'Applied for cross-trade maintenance role', completed: true },
      { stage: 'Screening', timestamp: '2026-02-27 11:30 AM', note: 'Under preliminary review for structural maintenance division', completed: true },
      { stage: 'Shortlisted', timestamp: '', note: '', completed: false },
      { stage: 'Interview', timestamp: '', note: '', completed: false },
      { stage: 'Selected', timestamp: '', note: '', completed: false },
      { stage: 'Hired', timestamp: '', note: '', completed: false },
    ],
  },
  {
    id: 'app_5',
    jobId: 'job_1',
    workerId: 'worker_suresh_2',
    employerId: 'employer_abc_1',
    jobTitle: 'Industrial Electrician & Substation Technician',
    companyName: 'ABC Industries Ltd.',
    workerName: 'Suresh Reddy',
    workerTrade: 'CNC Machinist',
    workerAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    workerTrustScore: 88,
    workerExperienceYears: 6,
    workerLocation: 'Hyderabad, Telangana',
    matchScore: 82,
    topSkills: ['Fanuc CNC', 'GD&T', 'Tool Offsets'],
    appliedDate: '2026-02-23',
    currentStage: 'Hired',
    timeline: [
      { stage: 'Applied', timestamp: '2026-02-23 10:00 AM', note: 'Applied with verified diploma', completed: true },
      { stage: 'Screening', timestamp: '2026-02-24 11:00 AM', note: 'Skills validated', completed: true },
      { stage: 'Shortlisted', timestamp: '2026-02-24 03:00 PM', note: 'Shortlisted for plant tour', completed: true },
      { stage: 'Interview', timestamp: '2026-02-26 11:00 AM', note: 'Passed on-site lathe calibration test', completed: true },
      { stage: 'Selected', timestamp: '2026-02-27 05:00 PM', note: 'Offer accepted', completed: true },
      { stage: 'Hired', timestamp: '2026-02-28 09:00 AM', note: 'Onboarded & ID Badge Generated (ID: ABC-EMP-881)', completed: true },
    ],
  },
];

export const mockVerifications: VerificationDocument[] = [
  {
    id: 'ver_1',
    workerOrEmployerId: 'worker_ramesh_1',
    entityName: 'Ramesh Kumar (Worker)',
    entityType: 'worker',
    docType: 'Aadhaar / National ID',
    docNumber: 'XXXX-XXXX-8921',
    submittedAt: '2026-02-20',
    status: 'verified',
    fileUrl: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    reviewedBy: 'Admin Moderator (Auto UIDAI)',
    reviewedAt: '2026-02-20',
  },
  {
    id: 'ver_2',
    workerOrEmployerId: 'worker_ramesh_1',
    entityName: 'Ramesh Kumar (Worker)',
    entityType: 'worker',
    docType: 'ITI Diploma',
    docNumber: 'NCVT-EL-2020-8849',
    submittedAt: '2026-02-21',
    status: 'verified',
    fileUrl: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=600&auto=format&fit=crop&q=80',
    reviewedBy: 'Admin Moderator',
    reviewedAt: '2026-02-21',
  },
  {
    id: 'ver_3',
    workerOrEmployerId: 'employer_abc_1',
    entityName: 'ABC Industries Ltd. (Employer)',
    entityType: 'employer',
    docType: 'GST Certificate',
    docNumber: '37AAACA4918L1Z9',
    submittedAt: '2026-02-18',
    status: 'verified',
    fileUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80',
    reviewedBy: 'Admin Moderator (GST Portal Match)',
    reviewedAt: '2026-02-19',
  },
  {
    id: 'ver_4',
    workerOrEmployerId: 'worker_suresh_2',
    entityName: 'Suresh Reddy (Worker)',
    entityType: 'worker',
    docType: 'Trade License',
    docNumber: 'AP-TL-2023-99120',
    submittedAt: '2026-02-27',
    status: 'pending',
    fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ver_5',
    workerOrEmployerId: 'worker_manjunath_4',
    entityName: 'Manjunath Patil (Worker)',
    entityType: 'worker',
    docType: 'Experience Letter',
    docNumber: 'PHE-EXP-2024-41',
    submittedAt: '2026-02-28',
    status: 'pending',
    fileUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80',
  },
];

export const mockReports: PlatformReport[] = [
  {
    id: 'rep_1',
    reporterName: 'Suresh Reddy',
    reportedEntityName: 'Shree Sai Manpower Agency',
    reportedEntityType: 'employer',
    reasonCategory: 'Fake Job',
    description: 'Demanded ₹2,500 upfront registration fee for a bogus factory job in Autonagar. Violates direct hiring policy.',
    status: 'pending',
    reportedAt: '2026-02-27',
    evidenceUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'rep_2',
    reporterName: 'ABC Industries Recruiter',
    reportedEntityName: 'Fake ITI Certificate Claim #910',
    reportedEntityType: 'certificate',
    reasonCategory: 'Fraudulent Certificate',
    description: 'Candidate presented photo-edited certificate without roll number on NCVT portal.',
    status: 'resolved',
    reportedAt: '2026-02-22',
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'user_worker_1',
    title: 'Interview Scheduled with ABC Industries!',
    message: 'Plant GM scheduled your on-site trade test for Industrial Electrician role on Monday at 10:00 AM.',
    type: 'interview',
    timestamp: '1 hour ago',
    isRead: false,
    actionUrl: '/worker/applications',
  },
  {
    id: 'notif_2',
    userId: 'user_worker_1',
    title: 'New 94% High Match Job Opening',
    message: 'ABC Industries posted "Industrial Electrician & Substation Tech" located 6 km from you in Vijayawada.',
    type: 'job_match',
    timestamp: '4 hours ago',
    isRead: false,
    actionUrl: '/worker/jobs/job_1',
  },
  {
    id: 'notif_3',
    userId: 'user_worker_1',
    title: 'Trust Score Updated to 91 / 100 🛡️',
    message: 'Your A-Grade Wireman License was verified by admin. Trust score increased by +12 points.',
    type: 'verification',
    timestamp: '1 day ago',
    isRead: true,
    actionUrl: '/worker/profile',
  },
  {
    id: 'notif_4',
    userId: 'user_employer_1',
    title: 'New High-Trust Applicant for Electrician Role',
    message: 'Ramesh Kumar (Trust Score 91, 5 yrs exp, ITI Verified) applied for your Industrial Electrician opening.',
    type: 'application_update',
    timestamp: '30 mins ago',
    isRead: false,
    actionUrl: '/employer/pipeline',
  },
];
