# Generated by Django 5.2.7 on 2026-08-29 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('category', models.CharField(db_index=True, default='General Trade', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('primary_trade', models.CharField(db_index=True, help_text='e.g. Industrial Electrician, CNC Machinist', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(default='Vijayawada, Andhra Pradesh', max_length=255)),
                ('city', models.CharField(db_index=True, default='Vijayawada', max_length=100)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100)),
                ('pin_code', models.CharField(default='520001', max_length=10)),
                ('preferred_radius_km', models.PositiveIntegerField(default=25)),
                ('availability', models.CharField(choices=[('available_now', 'Available Immediately'), ('in_two_weeks', 'Available in 2 Weeks'), ('employed_open', 'Employed but Open to Offers')], db_index=True, default='available_now', max_length=30)),
                ('expected_salary_min', models.PositiveIntegerField(default=25000)),
                ('expected_salary_max', models.PositiveIntegerField(default=32000)),
                ('years_of_experience', models.PositiveIntegerField(db_index=True, default=5)),
                ('education', models.CharField(default='ITI Electrical Diploma', max_length=255)),
                ('languages', models.JSONField(default=list, help_text='List of spoken languages')),
                ('profile_strength_percent', models.PositiveIntegerField(default=88)),
                ('trust_score_total', models.PositiveIntegerField(db_index=True, default=91)),
                ('trust_identity_score', models.PositiveIntegerField(default=20, help_text='Max 20 pts (Aadhaar biometric validation)')),
                ('trust_certifications_score', models.PositiveIntegerField(default=18, help_text='Max 20 pts (NCVT/CEIG verified certs)')),
                ('trust_skills_score', models.PositiveIntegerField(default=19, help_text='Max 20 pts (Standardized trade assessments)')),
                ('trust_experience_score', models.PositiveIntegerField(default=15, help_text='Max 15 pts (Employer-verified tenures)')),
                ('trust_reviews_score', models.PositiveIntegerField(default=10, help_text='Max 15 pts (Supervisor ratings)')),
                ('trust_completed_jobs_score', models.PositiveIntegerField(default=9, help_text='Max 10 pts (Authenticated photo proof of works)')),
                ('bookmarked_job_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trust_score_total', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200)),
                ('reviewer_company', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=5.0)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('verified_hire', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, default='Industrial Electrical', max_length=150)),
                ('images', models.JSONField(default=list, help_text='List of image URLs of completed machinery/installations')),
                ('skills_demonstrated', models.JSONField(default=list)),
                ('client_or_employer', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=200)),
                ('completion_date', models.DateField()),
                ('is_verified', models.BooleanField(db_index=True, default=True)),
                ('verified_by', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_works', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuing_body', models.CharField(help_text='e.g. NCVT, SCGJ, CEIG', max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(db_index=True, max_length=150, unique=True)),
                ('document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified ✓'), ('pending', 'Pending Verification'), ('rejected', 'Rejected')], db_index=True, default='verified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_skill', models.CharField(max_length=200)),
                ('unlocks_jobs_count', models.PositiveIntegerField(default=18)),
                ('avg_salary_boost', models.CharField(default='+₹8,000 / month', max_length=100)),
                ('course_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-unlocks_jobs_count'],
            },
        ),
        migrations.CreateModel(
            name='WorkerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=150)),
                ('category', models.CharField(default='Electrical', max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=5, help_text='Star rating 1 to 5')),
                ('years_experience', models.PositiveIntegerField(default=4)),
                ('is_verified', models.BooleanField(db_index=True, default=True)),
                ('verification_source', models.CharField(blank=True, help_text='e.g. NCVT Trade Assessment', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-level', '-years_experience'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('skills_used', models.JSONField(default=list)),
                ('is_employer_verified', models.BooleanField(db_index=True, default=True)),
                ('verifier_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['primary_trade', 'city'], name='workers_wor_primary_436263_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['trust_score_total', 'availability'], name='workers_wor_trust_s_a6300c_idx'),
        ),
    ]
