# Generated by Django 5.2.7 on 2026-08-29 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_alter_interview_options_interview_created_by_and_more"),
        ("employers", "0002_savedcandidate"),
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisorreview",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="applications.application",
            ),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="reliability_rating",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_reviews",
                to="employers.employerprofile",
            ),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="skill_rating",
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name="supervisorreview",
            name="reviewer_company",
            field=models.CharField(default="Industrial Employer", max_length=255),
        ),
        migrations.AlterField(
            model_name="supervisorreview",
            name="reviewer_name",
            field=models.CharField(default="Plant Supervisor", max_length=200),
        ),
    ]
