# Generated by Django 5.2.7 on 2026-08-29 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0002_supervisorreview_application_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["years_of_experience"], name="workers_wor_years_o_2de95b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["created_at"], name="workers_wor_created_b45581_idx"
            ),
        ),
    ]
