# Generated by Django 5.2.7 on 2026-08-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('worker', 'Worker'), ('employer', 'Employer')], db_index=True, default='worker', max_length=20)),
                ('doc_type', models.CharField(choices=[('Aadhaar / National ID', 'Aadhaar / National ID'), ('ITI Diploma', 'ITI Diploma'), ('Trade License', 'Trade License'), ('GST Certificate', 'GST Certificate'), ('Experience Letter', 'Experience Letter')], db_index=True, default='Aadhaar / National ID', max_length=50)),
                ('doc_number', models.CharField(db_index=True, max_length=150)),
                ('file_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('verified', 'Verified ✓'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='employers.employerprofile')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'entity_type'], name='verificatio_status_efa74f_idx'), models.Index(fields=['doc_type', 'status'], name='verificatio_doc_typ_808c78_idx')],
            },
        ),
    ]
