# Generated by Django 5.2.7 on 2026-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationdocument",
            name="document_file",
            field=models.FileField(
                blank=True, null=True, upload_to="verification_docs/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="verificationdocument",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("IDENTITY", "Identity / National ID"),
                    ("CERTIFICATE", "Trade / Technical Certificate"),
                    ("TRADE_LICENSE", "Trade License"),
                    ("OTHER", "Other Document"),
                    ("Aadhaar / National ID", "Aadhaar / National ID"),
                    ("ITI Diploma", "ITI Diploma"),
                    ("GST Certificate", "GST Certificate"),
                    ("Experience Letter", "Experience Letter"),
                ],
                db_index=True,
                default="IDENTITY",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="file_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("APPROVED", "Approved / Verified"),
                    ("REJECTED", "Rejected"),
                    ("verified", "Verified ✓"),
                    ("pending", "Pending Review"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
