# Generated by Django 5.2.7 on 2026-08-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('trade_category', models.CharField(db_index=True, default='Electrical', max_length=100)),
                ('location', models.CharField(default='Autonagar, Vijayawada', max_length=255)),
                ('city', models.CharField(db_index=True, default='Vijayawada', max_length=100)),
                ('distance_km', models.FloatField(default=6.0)),
                ('salary_min', models.PositiveIntegerField(db_index=True, default=25000)),
                ('salary_max', models.PositiveIntegerField(db_index=True, default=32000)),
                ('salary_period', models.CharField(default='monthly', max_length=20)),
                ('experience_required_years', models.PositiveIntegerField(default=4)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Contract', 'Contract'), ('Part-time', 'Part-time'), ('Shift-based', 'Shift-based')], db_index=True, default='Full-time', max_length=30)),
                ('shift', models.CharField(choices=[('Day Shift', 'Day Shift'), ('Night Shift', 'Night Shift'), ('Rotational', 'Rotational'), ('Flexible', 'Flexible')], default='Day Shift', max_length=30)),
                ('openings', models.PositiveIntegerField(default=4)),
                ('joining_date', models.CharField(default='Immediate / Within 15 Days', max_length=100)),
                ('deadline_date', models.CharField(default='2026-04-30', max_length=100)),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('required_certifications', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('benefits', models.JSONField(default=list)),
                ('work_address', models.CharField(default='Plot 42, Phase-2, Autonagar Industrial Area, Vijayawada, AP', max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.employerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trade_category', 'city', 'status'], name='jobs_job_trade_c_eeec94_idx'), models.Index(fields=['salary_min', 'salary_max'], name='jobs_job_salary__2892b4_idx')],
            },
        ),
    ]
