# Generated by Django 5.2.7 on 2026-08-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active / Open"),
                    ("paused", "Paused"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
