# Generated by Django 5.2.7 on 2026-08-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0002_savedcandidate"),
        ("jobs", "0003_savedjob"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "created_at"], name="jobs_job_status_277b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_type", "shift"], name="jobs_job_job_typ_47ac44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["experience_required_years"], name="jobs_job_experie_802c83_idx"
            ),
        ),
    ]
