# Generated by Django 5.2.7 on 2026-08-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Under Screening'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview / Trade Test'), ('Selected', 'Selected'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], db_index=True, default='Applied', max_length=30)),
                ('match_score', models.PositiveIntegerField(db_index=True, default=92, help_text='AI calculated compatibility percentage')),
                ('employer_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Under Screening'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview / Trade Test'), ('Selected', 'Selected'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='applications.application')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.CharField(default='10:00 AM IST', max_length=50)),
                ('interview_type', models.CharField(choices=[('In-person Trade Test', 'In-person Trade Test (Plant Workshop)'), ('Video Call', 'Video Technical Screening'), ('Phone Screening', 'Phone Screening'), ('Plant Visit', 'Plant Walkthrough')], default='In-person Trade Test', max_length=50)),
                ('location_or_link', models.CharField(default='ABC Industries Main Plant, Maintenance Bay 4, Autonagar, Vijayawada', max_length=300)),
                ('instructions', models.TextField(default='Please bring original trade certificates and safety boots.')),
                ('interviewer_name', models.CharField(default='K. Satyanarayana (General Manager - Operations)', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='applications.application')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'current_stage'], name='application_job_id_e5b198_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['worker', 'current_stage'], name='application_worker__54bf42_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['current_stage', 'match_score'], name='application_current_985e7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'worker')},
        ),
    ]
