# Generated by Django 5.2.7 on 2026-08-29 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interview",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="interview",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="location",
            field=models.CharField(
                default="Plant Maintenance Workshop, Vijayawada", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="meeting_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="current_stage",
            field=models.CharField(
                choices=[
                    ("Applied", "Applied"),
                    ("Screening", "Under Screening"),
                    ("Shortlisted", "Shortlisted"),
                    ("Interview", "Interview / Trade Test"),
                    ("Selected", "Selected"),
                    ("Hired", "Hired"),
                    ("Rejected", "Rejected"),
                    ("Withdrawn", "Withdrawn"),
                ],
                db_index=True,
                default="Applied",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="applicationtimelineevent",
            name="stage",
            field=models.CharField(
                choices=[
                    ("Applied", "Applied"),
                    ("Screening", "Under Screening"),
                    ("Shortlisted", "Shortlisted"),
                    ("Interview", "Interview / Trade Test"),
                    ("Selected", "Selected"),
                    ("Hired", "Hired"),
                    ("Rejected", "Rejected"),
                    ("Withdrawn", "Withdrawn"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="instructions",
            field=models.TextField(
                default="Please bring original trade certificates and government ID."
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="interview_type",
            field=models.CharField(
                choices=[
                    ("TRADE_TEST", "In-person Trade Test"),
                    ("VIDEO_CALL", "Video Technical Screening"),
                    ("IN_PERSON", "In-person Interview"),
                    ("PLANT_VISIT", "Plant Walkthrough"),
                    ("PHONE", "Phone Screening"),
                ],
                db_index=True,
                default="TRADE_TEST",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="interviewer_name",
            field=models.CharField(default="Plant Operations Team", max_length=200),
        ),
        migrations.AlterField(
            model_name="interview",
            name="location_or_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No Show"),
                ],
                db_index=True,
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
