# Generated by Django 5.2.7 on 2026-08-29 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(default='Community Member', max_length=200)),
                ('reported_entity_name', models.CharField(db_index=True, max_length=255)),
                ('reported_entity_type', models.CharField(choices=[('job', 'Job Posting'), ('employer', 'Employer / Plant'), ('worker', 'Worker'), ('certificate', 'Certificate')], db_index=True, default='employer', max_length=30)),
                ('reason_category', models.CharField(choices=[('Fake Job', 'Fake / Bogus Job Posting'), ('Fraudulent Certificate', 'Fraudulent Certificate'), ('Unsafe Workplace', 'Unsafe Workplace'), ('Harassment', 'Harassment'), ('Payment Default', 'Payment Default / Wage Delay')], db_index=True, default='Fake Job', max_length=50)),
                ('description', models.TextField()),
                ('evidence_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved / Suspended'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['status', 'reason_category'], name='reports_pla_status_f5702f_idx')],
            },
        ),
    ]
