# Generated by Django 5.2.7 on 2026-08-29 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="platformreport",
            name="reports_pla_status_f5702f_idx",
        ),
        migrations.RemoveField(
            model_name="platformreport",
            name="reason_category",
        ),
        migrations.AddField(
            model_name="platformreport",
            name="action_taken",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="platformreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("FAKE_JOB", "Fake / Misleading Job Posting"),
                    ("FAKE_CERTIFICATE", "Fake / Tampered Certificate"),
                    ("FRAUD", "Fraud / Extortion / Delayed Payment"),
                    ("INAPPROPRIATE_CONTENT", "Inappropriate / Offensive Content"),
                    ("OTHER", "Other Safety Issue"),
                ],
                db_index=True,
                default="FAKE_JOB",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="platformreport",
            name="reported_entity_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="platformreport",
            name="resolution_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformreport",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="platformreport",
            name="reported_entity_type",
            field=models.CharField(
                choices=[
                    ("job", "Job Posting"),
                    ("employer", "Employer / Plant"),
                    ("worker", "Worker"),
                    ("certificate", "Certificate"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="employer",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="platformreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("RESOLVED", "Resolved"),
                    ("DISMISSED", "Dismissed"),
                ],
                db_index=True,
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="platformreport",
            index=models.Index(
                fields=["status", "report_type"], name="reports_pla_status_3b46ea_idx"
            ),
        ),
    ]
